# Generated by Django 4.1.7 on 2023-02-27 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="proflie",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="profile_image/"),
        ),
        migrations.AddField(
            model_name="proflie",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
