# Generated by Django 4.1.7 on 2023-02-24 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roommseters", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="roommset",
            name="lifestaly",
            field=models.TextField(default="", max_length=750),
            preserve_default=False,
        ),
    ]
