# Generated by Django 4.1.7 on 2023-02-27 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("roommseters", "0003_roommset_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="roommset",
            old_name="type",
            new_name="type_seeker",
        ),
    ]
