# Generated by Django 4.1.7 on 2023-03-01 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roommseters', '0004_rename_type_roommset_type_seeker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roommset',
            name='avablie_at',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
