# Generated by Django 4.1.7 on 2023-03-01 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roommseters', '0005_alter_roommset_avablie_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='rommsetes/')),
            ],
        ),
        migrations.AlterField(
            model_name='roommset',
            name='type_seeker',
            field=models.CharField(blank=True, choices=[('seeker', 'seeker'), ('owner', 'owner')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='roommset',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images_room', to='roommseters.images'),
        ),
    ]
