# Generated by Django 4.1.7 on 2023-03-01 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roommseters', '0007_alter_images_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roommset',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images_room', to='roommseters.images'),
        ),
    ]
