# Generated by Django 4.1.7 on 2023-03-01 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roommseters', '0009_alter_roommset_image_delete_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='propery/')),
            ],
        ),
        migrations.AlterField(
            model_name='roommset',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images_room', to='roommseters.images'),
        ),
    ]
