# Generated by Django 4.1.7 on 2023-03-01 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roommseters', '0010_images_alter_roommset_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roommset',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images_room', to='roommseters.images'),
        ),
    ]
