# Generated by Django 4.1.7 on 2023-02-26 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="About",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("what_we_do", models.TextField(max_length=1000)),
                ("our_mission", models.TextField(max_length=1000)),
                ("our_goal", models.TextField(max_length=1000)),
                ("image", models.ImageField(upload_to="about/")),
                ("why_choose_us", models.TextField(max_length=1000)),
                ("email", models.EmailField(max_length=254)),
                ("contact_number", models.CharField(max_length=10)),
            ],
        ),
    ]
